name: wedly
description: "WEDLY - Luxury Wedding Booking Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.1.3

  # Icons
  cupertino_icons: ^1.0.2
  
  # Storage
  shared_preferences: ^2.2.2

  # Animations
  flutter_animate: ^3.0.0

  shimmer: ^3.0.0
  google_mobile_ads: ^5.3.1

  # Permissions
  permission_handler: ^11.1.0

  # API & Network
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Image Caching
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # JSON Code Generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/logo.png
    - assets/images/planing.png
    - assets/images/memories.png
    - assets/images/welcome.png
    - assets/images/
    - assets/images/004-wedding-arch.png
    - assets/images/008-wedding-car.png
    - assets/images/017-photography.png
    - assets/images/011-wedding-dinner.png    
    